### DISCUSSION TITLE
Can the graphs in Hourly forecasts  be disabled?

### DISCUSSION THREAD

**Discussion by 0323pin** [ttytm/wthrr-the-weathercrab#26] [Q&A] [answered]
Hi,

I would like to disable the graphs for the current day in the Hourly forecasts.
I'm clearly missing some characters in `FantasqueSansMono Nerd Font` or, on `alacritty`,

![2022-10-21-134925_675x740_scrot](https://user-images.githubusercontent.com/90570748/197189339-28fd02fa-8f0b-4faa-bc43-5ccf06fe46e1.png)

I don't want to change font or terminal, so the alternative would be to disable the graph.

Thanks.

**Comment by ttytm** [comment]
Thanks for opening the issue and info for reproduction!

Currently, it can not be disabled, unfortunately. 

I've scheduled some time in the next days to work on the app. I'll do my best to implement something like this and to fix the graph, so it works with more terminal/font combinations.

**Comment by ttytm** [comment]
Hey again @0323pin,

`FantasqueSans` is a font I'm also using in some of my dot files. So a reproduction was a super quick thing to do - hoping to also provide a quick fix for the problem.  

Due to the "oversized" nerd icons and the missing symbols, I guess the issue comes down to a not fully up-to-date version of the font that you are using. What's also visible on the screenshot is that the superscripted precipitation units are also not patched into that version. So disabling the graph would still result in missing icons. 

I've experienced similar problems with patched fonts when installing them via the package manager.
If you have installed it via the package manager, downloading it directly from the nerd-fonts repo and using that version is something you could try. [nerd-fonts/.../FantasqueSansMono](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/FantasqueSansMono)

This is how it looks reproducing the issue with latest `FantasqueSansMono Nerd Font Mono` version. 
left kitty ; right alacritty:
![Screenshot_20221022_121140](https://user-images.githubusercontent.com/34311583/197335941-7fbe726e-e175-4008-8ac9-dde98929fe6f.png)


There are still some small missplacements in the graph symbols which is down to alacritty not the font. I will check on the possibilites to fix this, but it's already usable I would say.

For now, would this be another alternative you are willing to use?

**Comment by 0323pin** [comment]
This looks good enough 😄 

I did fetch the font from the [nerdfonts site](https://www.nerdfonts.com/font-downloads).

I'll refetch them as it was probably over a year ago since I've installed them.

Would you mind sharing your `alacritty.yml`?
Here's mine, https://codeberg.org/pin/leftwm-netbsd/raw/branch/master/.config/alacritty/alacritty.yml

**Comment by ttytm** [comment]
Let me know how it goes. I think if it works, it's fair enough to have the latest nerd fonts as a requirement for the app to work.

Sure, I'll post it below. 
In the same breath, I have to admit that - as much as I am a Rust fanboy - alacritty never qualified to become one of my favorite tools. 
So the configuration file never went beyond a few minutes of messy basic setup with mainly just fonts and theme. Please forgive  for posting it without cleaning it up.

<details>
<summary>alacritty.yml</summary>

```yml
window:
  padding:
    x: 0
    y: 0

  opacity: 0.95

# Font configuration
font:
  normal:
    # Font family
    #
    # Default:
    #   - (macOS) Monaco
    #   - (Linux/BSD) monospace
    #   - (Windows) Consolas
    # family: JetBrainsMono Nerd Font Mono
    family: FantasqueSansMono Nerd Font Mono

    # The `style` can be specified to pick a specific face.
    style: Regular

  bold:
    # Font family
    #
    # If the bold family is not specified, it will fall back to the
    # value specified for the normal font.
    # family: Roboto Mono for Powerline

    # The `style` can be specified to pick a specific face.
    style: SemiBold

  italic:
    # Font family
    #
    # If the italic family is not specified, it will fall back to the
    # value specified for the normal font.
    # family: Roboto Mono for Powerline
    family: JetBrainsMono

    # The `style` can be specified to pick a specific face.
    style: Italic

  bold_italic:
    # Font family
    #
    # If the bold italic family is not specified, it will fall back to the
    # value specified for the normal font.
    # family: Roboto Mono for Powerline

    # The `style` can be specified to pick a specific face.
    style: SemiBold Italic

  # Point size
  size: 10

  # Offset is the extra space around each character. `offset.y` can be thought of
  # as modifying the line spacing, and `offset.x` as modifying the letter spacing.
  offset:
    x: 0
    y: 2

  # Glyph offset determines the locations of the glyphs within their cells with
  # the default being at the bottom. Increasing `x` moves the glyph to the right,
  # increasing `y` moves the glyph upwards.
  glyph_offset:
    x: 0
    y: 0

  # Thin stroke font rendering (macOS only)
  #
  # Thin strokes are suitable for retina displays, but for non-retina screens
  # it is recommended to set `use_thin_strokes` to `false`
  #
  # macOS >= 10.14.x:
  #
  # If the font quality on non-retina display looks bad then set
  # `use_thin_strokes` to `true` and enable font smoothing by running the
  # following command:
  #   `defaults write -g CGFontRenderingFontSmoothingDisabled -bool NO`
  #
  # This is a global setting and will require a log out or restart to take
  # effect.
  use_thin_strokes: true

# If `true`, bold text is drawn using the bright color variants.
# draw_bold_text_with_bright_colors: true

key_bindings:
# (Windows, Linux, and BSD only)
# - { key: Return,      action: None           }
#- { key: C,        mods: Control|Shift, action: Copy             }
#- { key: Insert,   mods: Shift,         action: PasteSelection   }
#- { key: Key0,     mods: Control,       action: ResetFontSize    }
 - { key: Equals,   mods: Control,       action: ResetFontSize }
 - { key: Plus,     mods: Control|Shift, action: IncreaseFontSize }
 - { key: Minus,    mods: Control,       action: DecreaseFontSize }

schemes:
  # Tokyo Night theme, based on both:
  #   https://github.com/ghifarit53/tokyonight-vim
  #   https://github.com/enkia/tokyo-night-vscode-theme
  tokyo-night: &tokyo-night # Default colors
    primary:
      # background: "0x1a1b26"
      # background: "0x222638"
      background: "0x282A36"
      foreground: "0xa9b1d6"

    # Normal colors
    normal:
      black: "0x32344a"
      red: "0xf7768e"
      green: "0x9ece6a"
      yellow: "0xe0af68"
      blue: "0x7aa2f7"
      magenta: "0xad8ee6"
      cyan: "0x449dab"
      white: "0x787c99"

    # Bright colors
    bright:
      black: "0x444b6a"
      red: "0xff7a93"
      green: "0xb9f27c"
      yellow: "0xff9e64"
      blue: "0x7da6ff"
      magenta: "0xbb9af7"
      cyan: "0x0db9d7"
      white: "0xacb0d0"

  tokyo-night-storm: &tokyo-night-storm # Default colors
    primary:
      background: "0x24283b"
      foreground: "0xa9b1d6"

    # Normal colors
    normal:
      black: "0x32344a"
      red: "0xf7768e"
      green: "0x9ece6a"
      yellow: "0xe0af68"
      blue: "0x7aa2f7"
      magenta: "0xad8ee6"
      cyan: "0x449dab"
      white: "0x9699a8"

    # Bright colors
    bright:
      black: "0x444b6a"
      red: "0xff7a93"
      green: "0xb9f27c"
      yellow: "0xff9e64"
      blue: "0x7da6ff"
      magenta: "0xbb9af7"
      cyan: "0x0db9d7"
      white: "0xacb0d0"

    # Dracula theme for Alacritty
    # https://draculatheme.com/alacritty
    #
    # Color palette
    # https://spec.draculatheme.com
    #
    # Template
    # https://github.com/alacritty/alacritty/blob/master/alacritty.yml

  dracula: &dracula
    primary:
      background: "#282a36"
      foreground: "#f8f8f2"
      bright_foreground: "#ffffff"
    cursor:
      text: CellBackground
      cursor: CellForeground
    vi_mode_cursor:
      text: CellBackground
      cursor: CellForeground
    search:
      matches:
        foreground: "#44475a"
        background: "#50fa7b"
      focused_match:
        foreground: "#44475a"
        background: "#ffb86c"
      bar:
        background: "#282a36"
        foreground: "#f8f8f2"
    hints:
      start:
        foreground: "#282a36"
        background: "#f1fa8c"
      end:
        foreground: "#f1fa8c"
        background: "#282a36"
    line_indicator:
      foreground: None
      background: None
    selection:
      text: CellForeground
      background: "#44475a"
    normal:
      black: "#21222c"
      red: "#ff5555"
      green: "#50fa7b"
      yellow: "#f1fa8c"
      blue: "#bd93f9"
      magenta: "#ff79c6"
      cyan: "#8be9fd"
      white: "#f8f8f2"
    bright:
      black: "#6272a4"
      red: "#ff6e6e"
      green: "#69ff94"
      yellow: "#ffffa5"
      blue: "#d6acff"
      magenta: "#ff92df"
      cyan: "#a4ffff"
      white: "#ffffff"

colors: *tokyo-night
```
</details>

**Comment by 0323pin** [comment]
@tobealive Using `family: FantasqueSansMono Nerd Font Mono` instead of `family: FantasqueSansMono Nerd Font` made a difference. I've re-fetched the font as well, still, I have to dig deeper.

Here's how it looks now
![2022-10-22-224720_1358x740_scrot](https://user-images.githubusercontent.com/90570748/197361861-51319ac2-c64f-4ad1-9c0d-878378723a63.png)

As you can see, there are still issues. Also, I don't know why colors are missing but, as said, I'll dig further.

**Comment by ttytm** [comment]
Okay, seems we are coming closer.

Running kitty in font debug mode I found out that the terminal uses `NotoSansMono-Regular` for the superscripted precipitation unit icons. But I could not get info on the graph icons yet - might also be NotoSans. 

Alacritty will most certainly have a debug mode too. Does it tell you which font is missing then?

**Comment by 0323pin** [comment]
`alacritty -v` outputs nothing useful, increasing the verbose level, I get the following

```
> alacritty -vv
...
[5.831237229s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[5.835325552s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Roman, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }

> alacritty -vvv
...
[7.730173262s] [TRACE] [crossfont] Got font path="/usr/X11R7/lib/X11/fonts/TTF/Vera.ttf", index=0
[7.730653494s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Roman, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
```

Wonder why it's looking for other fonts. Apparently, looking for a Roman variant.

```
font:
  normal:
    family: FantasqueSansMono Nerd Font Mono
    style: Regular

  bold:
    family: FantasqueSansMono Nerd Font Mono
    style: Bold

  italic:
    family: FantasqueSansMono Nerd Font Mono
    style: Italic

  bold_italic:
    family: FantasqueSansMono Nerd Font Mono
    style: Bold Italic

  size: 8.5
```
